### ISSUE TITLE
Unicode to UTF-8

### ISSUE THREAD

**Issue by diplomatech** [OliverCi/freeplane2md#14]
My Freeplane maps is written in portuguese language, which has accented characters. So, the freeplane2md converted all that accented characters to a fixed character code. I changed the freeplane2md.py code, at line 191, to solve this problem. There I added the parameter `encoding = 'UTF-8'` to the `open(markdown_path, 'w')`... => `open(markdown_path, 'w', 'UTF-8')`.

**Comment by OliverCi** [comment]
Good point. The current behavior depends on the system configuration. I'll include forcing UTF-8 in the next version.
